spring:
  application:
    name: kafka-template-sample

#    ssl:
#      bundle:
#        jks:
#          secure-service:
#            key:
#              alias: "secure-service"
#            keystore:
#              location: "classpath:keystore.p12"
#              password: "FooBar"
#              type: "PKCS12"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      bootstrap-servers: ${kafkaprops.bootstrapServers}
      acks: ${kafkaprops.acks}
      client-id: ${kafkaprops.clientId}
      properties:
        enable.idempotence: ${kafkaprops.enableIdempotence}
        schema.registry.url: ${kafkaprops.schemaRegistryUrl}
        auto.register.schemas: false
        use.latest.version: true
